### ISSUE TITLE
Error on import, pydantic V2[BUG]

### ISSUE THREAD

**Issue by arrpii** [roman-right/bunnet#14]
I get this error when I try to import bunnet to my project:

```
Traceback (most recent call last):
  File "C:\Users\robin\Desktop\test\test.py", line 1, in <module>
    import bunnet
  File "C:\Users\robin\Desktop\test\venv\lib\site-packages\bunnet\__init__.py", line 1, in <module>
    from bunnet.migrations.controllers.free_fall import free_fall_migration
  File "C:\Users\robin\Desktop\test\venv\lib\site-packages\bunnet\migrations\controllers\free_fall.py", line 4, in <module>
    from bunnet.odm.documents import Document
  File "C:\Users\robin\Desktop\test\venv\lib\site-packages\bunnet\odm\documents.py", line 17, in <module>
    from lazy_model import LazyModel
  File "C:\Users\robin\Desktop\test\venv\lib\site-packages\lazy_model\__init__.py", line 1, in <module>
    from lazy_model.main import LazyModel, NAO
  File "C:\Users\robin\Desktop\test\venv\lib\site-packages\lazy_model\main.py", line 5, in <module>
    from pydantic.error_wrappers import ErrorWrapper
  File "C:\Users\robin\Desktop\test\venv\lib\site-packages\pydantic\_migration.py", line 295, in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic.error_wrappers:ErrorWrapper` has been removed in V2.

For further information visit https://errors.pydantic.dev/2.1.1/u/import-error
```
Seems like bunnet is not compatible with pydantic V2.
If I use pydantic V1 instead it works.

Are there plans to support pydantic V2? Maybe an intermediate fix could be to limit the package dependency to pydantic V1?

**Comment by roman-right** [comment]
Hi. Bunnet doesn't support v2 yet. I'm working on it atm

**Comment by arrpii** [comment]
Great to hear, I was mainly flagging it since pip will pick up pydantic v2 by default if you "pip install bunnet".

**Comment by mkhorton** [comment]
Hello, I was wondering if there was any update on pydantic v2 support in `bunnet`? I saw it's working nicely in `beanie`. Thanks for the great work!

**Comment by roman-right** [comment]
Hi! I'm working on this. I expect it to be published by the end of the next week.

**Comment by mkhorton** [comment]
Hi Roman, any update on this issue? We're starting to run into a lot of dependency resolution problems now that other libraries have moved to pydantic v2.

Leaving this comment with no expectation for resolution and full appreciation for your open source efforts on this library! It's not taken for granted at all.

**Comment by roman-right** [comment]
It was published today. The version is `1.2.0`
Please, try

**Comment by mkhorton** [comment]
Thanks so much! I can only imagine the effort. Will try/test now and report back if we see any issues.
